Fix printf

diff --git a/' b/'
--- a/'
+++ b/'
@@ -51,14 +51,14 @@ refreshkeys() { \
 
 checkpkginstall() {
 	printf "Checking if $1 is installed\\n"
-	(pacman -Qi "$1" > /dev/null 2>&1 || pacman -Qg "$1" > /dev/null 2>&1) && printf "$1 is installed\\n" || (printf "$1 is not installed\\n" && exit 1)
+	(pacman -Qi "$1" > /dev/null 2>&1 || pacman -Qg "$1" > /dev/null 2>&1) && printf "$1 is installed\\n" || (printf "$1 is not installed" && exit 1)
 }
 
 manualinstall() {
 	# Installs $1 manually. Used only for AUR helper here.
 	# Should be run after repodir is created and var is set.
 	pacman -Qq "$1" && return 0
-	printf "Installing $1 from AUR manually.\\n"
+	printf "Installing $1 from AUR manually."
 	sudo -u "$name" mkdir -p "$repodir/$1"
 	sudo -u "$name" git -C "$repodir" clone --depth 1 --single-branch \
 		--no-tags -q "https://aur.archlinux.org/$1.git" "$repodir/$1" ||
@@ -73,7 +73,7 @@ manualinstall() {
 
 maininstall() {
 	# Installs all needed programs from main repo.
-	printf "Installing $1 ($n of $total). $1 $2\\n"
+	printf "Installing $1 ($n of $total). $1 $2"
 	installpkg "$1"
 }
 
@@ -81,7 +81,7 @@ gitmakeinstall() {
 	progname="${1##*/}"
 	progname="${progname%.git}"
 	dir="$repodir/$progname"
-	printf "Installing $progname ($n of $total) via \`git\` and \`make\`. $(basename "$1") $2\\n"
+	printf "Installing $progname ($n of $total) via \`git\` and \`make\`. $(basename "$1") $2"
 	sudo -u "$name" git -C "$repodir" clone --depth 1 --single-branch \
 		--no-tags -q "$1" "$dir" ||
 		{
@@ -95,13 +95,13 @@ gitmakeinstall() {
 }
 
 aurinstall() {
-	printf "Installing $1 ($n of $total) from the AUR. $1 $2\\n"
+	printf "Installing $1 ($n of $total) from the AUR. $1 $2"
 	echo "$aurinstalled" | grep -q "^$1$" && return 1
 	sudo -u "$name" $aurhelper -S --noconfirm "$1" >/dev/null 2>&1
 }
 
 pipinstall() {
-	printf "Installing the Python package $1 ($n of $total). $1 $2\\n"
+	printf "Installing the Python package $1 ($n of $total). $1 $2"
 	[ -x "$(command -v "pip")" ] || installpkg python-pip >/dev/null 2>&1
 	yes | pip install "$1"
 }
@@ -126,7 +126,7 @@ installationloop() {
 
 putgitrepo() {
 	# Downloads a gitrepo $1 and places the files in $2 only overwriting conflicts
-	printf "Downloading and installing config files...\\n"
+	printf "Downloading and installing config files..."
 	[ -z "$3" ] && branch="master" || branch="$repobranch"
 	dir=$(mktemp -d)
 	[ ! -d "$2" ] && mkdir -p "$2"
@@ -140,7 +140,7 @@ putgitrepo() {
 vimplugininstall() {
 	# TODO remove shortcuts error message
 	# Installs vim plugins.
-	printf "Installing neovim plugins...\\n"
+	printf "Installing neovim plugins..."
 	mkdir -p "/home/$name/.config/nvim/autoload"
 	curl -Ls "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" >  "/home/$name/.config/nvim/autoload/plug.vim"
 	chown -R "$name:wheel" "/home/$name/.config/nvim"
@@ -156,7 +156,7 @@ finalize(){
 ### This is how everything happens in an intuitive format and order.
 
 name=`who am i | awk '{print $1}'`
-printf "Running as user $name\\n"
+printf "Running as user $name"
 
 # Check if user is root on Arch distro. Install dialog.
 ! [ $(id -u) = 0 ] && error "Must run the script as root"
@@ -167,10 +167,10 @@ printf "Running as user $name\\n"
 refreshkeys || error "Error automatically refreshing Arch keyring. Consider doing so manually."
 
 for x in curl ca-certificates base-devel git ntp zsh; do
-	checkpkginstall "$x" || (printf "Installing $x which is required to install and configure other programs.\\n" && installpkg "$x") || error "Failed to install $x"
+	checkpkginstall "$x" || (printf "Installing $x which is required to install and configure other programs." && installpkg "$x") || error "Failed to install $x"
 done
 
-printf "Synchronizing system time to ensure successful and secure installation of software...\\n"
+printf "Synchronizing system time to ensure successful and secure installation of software..."
 ntpd -q -g >/dev/null 2>&1
 
 # Allow user to run sudo without password. Since AUR programs must be installed
@@ -213,7 +213,7 @@ sudo -u "$name" mkdir -p "/home/$name/.cache/zsh/"
 sudo -u "$name" mkdir -p "/home/$name/.config/mpd/playlists/"
 
 # Enable tap to click
-[ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && echo 'Section "InputClass"
+[ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && printf 'Section "InputClass"
         Identifier "libinput touchpad catchall"
         MatchIsTouchpad "on"
         MatchDevicePath "/dev/input/event*"
